Rails/odin-flight-booker-2/config/routes.rb
OdinFlightBooker2::Application.routes.draw do
  root "flights#index"

  get "flights/" => 'flights#index'
  resources :bookings, only: [:new, :create, :show]

end

Rails/odin-flight-booker-2/app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, class_name: "Flight", foreign_key: :from_airport_id
  has_many :arriving_flights, class_name: "Flight", foreign_key: :to_airport_id
  
end

Rails/odin-flight-booker-2/app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many   :tickets, foreign_key: :booking_id
  has_many   :passengers, through: :tickets
  belongs_to :flight

  accepts_nested_attributes_for :passengers
end

Rails/odin-flight-booker-2/app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"

  has_many :bookings, foreign_key: :flight_id
  has_many :passengers, through: :bookings

  #in order for the datetime to be called correctly, we need to have an array like so
  def self.flight_dates
    all.map { |f| [f.formatted_date, f.date.to_date] }.uniq
  end

  def self.search(params)
    if params[:search]
      Flight.on_date(params[:date].to_date)
            .where('from_airport_id = ? AND to_airport_id = ?', params[:from], params[:to])
            .includes(:from_airport, :to_airport) # prevents N + 1 queries
    else
      Flight.none
    end
  end

  def self.on_date(date_param)
    where(date: date_param.beginning_of_day..date_param.end_of_day)
  end

  def formatted_date
    date.strftime("%m/%d/%Y")
  end

end

Rails/odin-flight-booker-2/app/models/passenger.rb
class Passenger < ActiveRecord::Base

  has_many  :tickets, foreign_key: :passenger_id
  has_many  :bookings, through: :tickets
  has_many  :flights, through: :bookings
end

Rails/odin-flight-booker-2/app/models/ticket.rb
class Ticket < ActiveRecord::Base

  belongs_to :passenger
  belongs_to :booking
end

Rails/odin-flight-booker-2/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build

    params[:passengers].to_i.times { @booking.passengers.build }
    @booking.passengers.build if params[:passengers].blank? 
    redirect_to root_path if params[:flight_id].nil?
  end

  def create
    @booking = Booking.create(booking_params)
    if @booking.save
      
      @booking.passengers.each { |p| PassengerMailer.thankyou_email(p).deliver! }

      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

Rails/odin-flight-booker-2/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.pluck(:code, :id)
    @dates = Flight.flight_dates
    @passengers = (1..4).map { |x| [x.to_s, x]}
    @flights = Flight.search(params)
    if @flights.none? 
      flash[:error] = "No flights."
    else
      flash[:success] = "Check flights below."
    end
  end
end

Rails/odin-flight-booker-2/app/helpers/bookings_helper.rb
module BookingsHelper
end

Rails/odin-flight-booker-2/app/helpers/flights_helper.rb
module FlightsHelper
end

Rails/odin-flight-booker-2/app/views/flights/_flight.html.erb
<%= form_tag new_booking_path, method: "get" do %>  
  <table>
    <thead>
      <tr>
        <th>Select</th>
        <th>Flight #</th>
        <th>Day</th>
        <th>Time</th>    
        <th>From</th>    
        <th>To</th>
        <th>Duration</th>
      </tr>
    </thead>  
    <tbody>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= radio_button_tag :flight_id, flight.id %></td>
          <td><%= flight.id %></td>
          <td><%= flight.date.strftime("%B %d, %Y")  %></td>
          <td><%= flight.date.strftime('%I:%M:%S %p') %></td>
          <td><%= flight.from_airport.code %></td>
          <td><%= flight.to_airport.code %></td>
          <td><%= distance_of_time_in_words(flight.duration) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <br>
  <%= submit_tag "Select This Flight", name: nil %>
  <%= hidden_field_tag :passengers, params[:passengers] %>
<% end %>

Rails/odin-flight-booker-2/app/views/flights/_searchbar.html.erb
<%= form_tag flights_path, method: "get" do %>
  <%= hidden_field_tag :search%>
  <!-- options_for_select puts the @airport's first element as the text value, second element
          is the real value saved  -->
  <%= select_tag :from, options_for_select(@airports), prompt: "From" %>
  <%= select_tag :to, options_for_select(@airports), prompt: "To" %>
  <%= select_tag :date, options_for_select(@dates), prompt: "Date" %>
  <%= select_tag :passengers, options_for_select(@passengers), prompt: "Passengers" %>
  <%= submit_tag "Search Flights", name: nil %> 
<% end %>

Rails/odin-flight-booker-2/app/views/flights/index.html.erb
<h1>Flights#index</h1>
<p>Find me in app/views/flights/index.html.erb</p>

<%= render "searchbar" %>


<% if @flights.any? %>

  <%= render 'flight' %>
  
<% else %>
  <% "No Flights" %>
<% end %>