Rails/odin-kittens/config/routes.rb
OdinKittens::Application.routes.draw do
  root "kittens#index"
  resources :kittens

end

Rails/odin-kittens/app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

Rails/odin-kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(user_params)
    if @kitten.save
      redirect_to @kitten, notice: "Your kitten was purrr-fectly created."
    else
      render 'new'
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(user_params)
      flash[:success] = "Kitten was purrr-fectly updated."
      redirect_to @kitten
    else
      render 'edit'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id]).delete
    redirect_to root_path
  end

  private

  def user_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

Rails/odin-kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

Rails/odin-kittens/app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
  <% if @kitten.errors.any? %>
    Fix <%= pluralize(@kitten.errors.count, "error") %> to enter this kitten.

    <% @kitten.errors.full_messages.each do |e| %>
      <%= e %>
    <%end %>
  <% end %>
  
  <div>
    <%= f.text_field   :name,     placeholder: "Name",    required: true %>
  </div>
  <div>
    <%= f.number_field :age,      placeholder: "Age",     required: true %>
  </div>
  <div>
    <%= f.number_field :cuteness, placeholder: "Cuteness",required: true %>
  </div>
  <div>
    <%= f.number_field :softness, placeholder: "Softness",required: true %>
  </div>
    <%= f.submit "Enter kitten" %>
<% end %>

Rails/odin-kittens/app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

Rails/odin-kittens/app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

Rails/odin-kittens/app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<p>Find me in app/views/kittens/edit.html.erb</p>

<%= render "form" %>

Rails/odin-kittens/app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<p>Find me in app/views/kittens/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |k| %>
      <tr>
        <td><%= k.name %></td> 
        <td><%= k.age %></td> 
        <td><%= k.cuteness %></td> 
        <td><%= k.softness %></td> 
        <td><%= link_to "Details", k %></td>
        <td><%= link_to "Edit", edit_kitten_path(k) %></td>
        <td><%= link_to "Delete", k, method: :delete, 
                                        confirm: "Are you sure?" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to "Enter new kitten", new_kitten_path %></td>

Rails/odin-kittens/app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
<p>Find me in app/views/kittens/new.html.erb</p>

<strong>Enter a new Kitten</strong>

  <%= render "form" %>

<br>
  <%= link_to "Back", root_path %>

Rails/odin-kittens/app/views/kittens/show.html.erb
<h1>Kittens#show</h1>
<p>Find me in app/views/kittens/show.html.erb</p>

<p>
  1. You're cute Kitten is called <strong><%= @kitten.name %></strong>.
</p>

<p>
  2. It's <strong><%= @kitten.age %></strong> years old.
</p>

<p>
  3. It's <strong><%= @kitten.cuteness %>x</strong> cuter than the normal kitten.
</p>

<p>
  4. It's <strong><%= @kitten.softness %>x</strong> soft.
</p>

<%= link_to "Delete kitten", @kitten, method: :delete, confirm: "Are you sure?" %>

<br>
  <%= link_to "Back", root_path %>

Rails/odin-kittens/app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

Rails/odin-kittens/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>    
  
  <div class="container" color="red">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>